@startuml ClassExam

class Etudiant{
    numéro
    nom
    prénom
    DateDeNaissance
}

class Cours{
    Titre
    CodeModule
}

class Examen{
    DateExam
    Coefficient
}

class Enseignant{
    nom
    prénom
}

Etudiant "1..*" -- "0..*" Examen 
Etudiant "1..*" -- "1..*" Cours
Enseignant "1..*" -- "1" Cours
Examen "*" -- "1" Cours
(Etudiant, Examen) . Note


@enduml
