@startuml ClassExam

class Etudiant{
    numéro
    nom
    prénom
    DateDeNaissance
}

class Cours{
    Titre
    CodeModule
}

class Examen{
    DateExam
    Coefficient
}

class Enseignant{
    nom
    prénom
}

class Note{
    note
}

Etudiant "1..*" -- "1..*" Cours
Enseignant "1..*" -- "1" Cours
Examen "1" -- "1" Cours
Note "1" -- "1" Etudiant
Note "1" -- "1" Examen


@enduml