@startuml ClassExam

class Etudiant{
    numéro
    nom
    prénom
    DateDeNaissance
}

class Cours{
    Titre
    CodeModule
}

class Examen{
    DateExam
    Coefficient
}

class Enseignant{
    nom
    prénom
}

(Etudiant, Examen) .. Note


Etudiant "1..*" -- "1..*" Cours
Enseignant "1..*" -- "1" Cours
Examen "1" -- "1" Cours


@enduml
